Deprecation notice
graphql/express-graphql pull request #817
Opened 2022-11-10 19:29 UTC by enisdenjo

Deprecating express-graphql in favour of [graphql-http](https://github.com/graphql/graphql-http) being now the official implementation.

[Read more about it here.](https://graphql.org/blog/2022-11-07-graphql-foundation-graphql-http/)

### TODO

- [ ] Archive repo
- [ ] Deprecate npm package

2022-11-11 10:51 UTC, Urigo approved these changes

2022-11-11 20:33 UTC, saihaj approved these changes

2022-11-14 08:19 UTC, dotansimha approved these changes

2022-11-15 10:44 UTC, benjie requested changes

2022-11-15 10:44 UTC, benjie commented on README.md
> +- [`mercurius`](https://mercurius.dev/) ([partially compliant](https://github.com/enisdenjo/graphql-http/tree/master/implementations/mercurius))
"Partially compliant" seems uncharitable; they're all fully compliant in that they implement all the MUSTs. Yoga is fully compliant _including_ implementing optional features such as `GET` and the various `SHOULD`s, and is watershed-ready.

Also, we should invite people to link their own servers here.

```suggestion
- [`graphql-yoga`](https://www.the-guild.dev/graphql/yoga-server) ([fully compliant (0 warnings)](https://github.com/enisdenjo/graphql-http/tree/master/implementations/graphql-yoga), [migration guide](https://www.the-guild.dev/graphql/yoga-server/v3/migration/migration-from-express-graphql))
- [`apollo-server`](https://www.apollographql.com/docs/apollo-server/) ([compliant](https://github.com/enisdenjo/graphql-http/tree/master/implementations/apollo-server))
- [`mercurius`](https://mercurius.dev/) ([compliant](https://github.com/enisdenjo/graphql-http/tree/master/implementations/mercurius))

To add your server to this list, please first add an implementation test to https://github.com/enisdenjo/graphql-http/tree/master/implementations/
```

@enisdenjo I'm not sure if this is the link you want to send people to, just a suggestion

2022-11-16 12:56 UTC, merged